### ISSUE TITLE
where can I found the book for this code

### ISSUE THREAD

**Issue by BuffaloBorn** [PacktPublishing/AWS-Certified-DevOps-Engineer-Professional-Certification-and-Beyond#2]
I've been looking for the book that is published by packt that supports this code. Can you point me to the exact book on Packt website?

**Comment by ArjunVarma39** [comment]
Hello @BuffaloBorn,

This book is not yet published and will be available for purchase in the month of Nov 2021 on all our platforms. After the title has been published, the README.MD file will be updated with all of the title's available links.

Thank you!
