### ISSUE TITLE
Ch8 codeBuild exercise missing some steps and code errors

### ISSUE THREAD

**Issue by worthlesspenny7** [PacktPublishing/AWS-Certified-DevOps-Engineer-Professional-Certification-and-Beyond#4]
I couldn't get the "devops" user to login to docker until I added this policy: [AWSAppRunnerServicePolicyForECRAccess](https://console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess)

buildspec.yml diff:
```
+env:
+  variables:
+    AWS_ACCOUNT_ID: "## Account ID ##"
+    IMAGE_REPO_NAME: "chapter8_codebuild"
+    IMAGE_TAG: "latest"
```

install phase missing commands: subsection
```-  install:```

all phases under install mis-indented
[diff not shown for brevity]

```
-        - docker push AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
+      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
```

Dockerfile diff:
```
+ENV TZ=Etc/UTC
+ENV DEBIAN_FRONTEND=noninteractive

-RUN apt-get install -y python-3 pip python-dev build-essential git 
+RUN apt-get install -y python3 pip python-dev build-essential git
```

This got me to finish the docker build, but still times out when pushing to the ECR. I'll update if I invest more time and have success.

**Comment by nithikpackt** [comment]
Thank you @worthlesspenny7  for the solution
